BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXBBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBBBBBBB
            FFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXXXX
                    XX
                  XXXXXXX
                XXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
