BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXXBBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            FFFFFF
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX
    XXXXXX

BBBBBBBB BBBBBBB