# Generated by Django 5.0.2 on 2024-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='National_ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 1), ('Female', 2), ('Other', 3)], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nat_id',
            field=models.CharField(max_length=10, verbose_name='National_ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
    ]
