# Generated by Django 5.0.2 on 2024-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='FatherName'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1, verbose_name='Gender'),
        ),
    ]
